### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DomenRok** [DomenRok/WebScrape#2]
- [ ] Properly handle forms

- [ ] Properly handle file download/scrape

- [ ] Setup a production enviorment

- [ ] create a docker image

- [ ] migrate from sqlite to PostgreSQL 

- [ ] Add Continous Integration (TRAVIS CI)
